### ISSUE TITLE
Циклическая зависимость

### ISSUE THREAD

**Issue by i-panov** [yandex/yx_scope#3]
Здравствуйте! Прочитал про вашу либу на Хабре. Попробовал прикрутить. Вот такая проблема (упрощенно):

```
class A {
  final C c;
  A(this.c);
}

class B {
  final A a;
  B(this.a);
}

class C {
  final B b;
  C(this.b);
}
```

Как бы вы это зарегистрировали как зависимости с вашей библиотекой? Все 3 класса должны быть зарегистрированы.

**Comment by GalimzyanovDanil** [comment]
@i-panov  Судя по всему никак. Так как в линтере `yx_scope_linter` даже есть [правило](https://pub.dev/packages/yx_scope_linter#dep_cycle) запрещающее это делать

**Comment by i-panov** [comment]
@GalimzyanovDanil но логика приложения требует именно такой зависимости... Ясно. Остаюсь на GetIt. 🤷

**Comment by kltsv** [comment]
@GalimzyanovDanil и @meg4cyberc4t всё верно ответили — циклическая зависимость это антипаттерн, который мы наоборот стараемся не допустить в библиотеке.

В вашем случае можно попробовать "разорвать" цепочку: выделить класс таким образом, чтобы он содержал общую логику для остальных классов и им не приходилось зависеть друг на друга, а только на этот выделенный класс. Либо ввести ещё одну зависимость D, которая возьмет на себя роль такого класса.

Issue закрываю, потому что такая функциональность явно противоречит исходной парадигме, в которой сделана библиотека.
